spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: medical-care-service
          uri: lb://medical-care-service
          predicates:
            - Path=/medical-care/**
          filters:
            - RewritePath=/medical-care/(?<path>.*), /$\{path}
        - id: health-monitor-service
          uri: lb://health-monitor-service
          predicates:
            - Path=/health-monitor/**
          filters:
            - RewritePath=/health-monitor/(?<path>.*), /$\{path}

server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"