spring:
  cloud:
    stream:
      function:
        definition: healthInfoSupplier; healthInfoConsumer; medicalInstructionConsumer

      bindings:
        healthInfoSupplier-out-0:
          destination: health-info
        healthInfoConsumer-in-0:
          destination: health-info
        anomaly-out-0:
          destination: anomaly
        medicalInstructionConsumer-in-0:
          destination: medicalInstruction

      kafka:
        binder:
          zkNodes: kafka
          brokers: kafka
          replication-factor: 1

  redis:
    host: redis
    port: 6379
    database: 0
    password: my-secret

  data:
    mongodb:
      host: mongo
      port: 27017
      database: health-monitor

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/