spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: medical-care

  cloud:
    stream:
      function:
        definition: anomalySupplier; anomalyConsumer

      bindings:
        anomalyConsumer-in-0:
          destination: anomaly
        medicalInstruction-out-0:
          destination: medicalInstruction

      kafka:
        binder:
          zkNodes: kafka
          brokers: kafka
          replication-factor: 1

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

server:
  port: 8090
