spring:
  cloud:
    stream:
      function:
        definition: healthInfoSupplier; healthInfoConsumer

      bindings:
        healthInfoSupplier-out-0:
          destination: health-info
        healthInfoConsumer-in-0:
          destination: health-info
        anomaly-out-0:
          destination: anomaly

      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
          replication-factor: 1

  data:
    mongodb:
      host: localhost
      port: 27017
      database: healthInfo