FROM openjdk:17-jdk-slim

RUN apt-get update && apt-get install -y curl

ARG APP_NAME="configserver"
ARG APP_VERSION="0.0.1"
ARG JAR_FILE="/build/libs/${APP_NAME}-${APP_VERSION}-SNAPSHOT.jar"

EXPOSE 8071
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar", "app.jar"]
